import React from "react";
import { useNavigate } from 'react-router-dom';
import "./SaibaMais.css"
import TopBarPropDesktop from "../prefabs/TobBarMenu/TopBarMenu";

const SaibaMais = () =>{
    const navigate = useNavigate();
    return(
        <div id="SaibaMaisPage">
             <TopBarPropDesktop styles={{ listStyle: 'none', margin: 0, padding: 0 }} />
            <h2 className="title-descricao">POLÍTICAS INFORMADAS POR EVIDÊNCIAS: O QUE SÃO?</h2>
            <div className= "TextGrup">
                <p  className="text-SaibaMais"><b> O termo Políticas Informadas por Evidências (PIE)</b> aplica-se aos processos sistemáticos e transparentes para a incorporação das melhores evidências disponíveis para abordar problemas e identificar opções de enfrentamento e propor estratégias de implementação. As Políticas e serviços de saúde informados por evidências são uma tendência mundial na busca de melhores resultados com recursos limitados, principalmente nos países em desenvolvimento, onde estruturação e expansão de sistemas e serviços de saúde ainda se fazem presentes. </p>
                <p  className="text-SaibaMais">As <b>Redes Nacionais de Pesquisa em Saúde (RNPS)</b> são articulações cooperativas entre instituições de ciência, tecnologia, inovação e produção em saúde, públicas e privadas, e pesquisadores, que visam o desenvolvimento científico e tecnológico que priorize as necessidades e demandas do Sistema Único de Saúde (SUS). As RNPS adotam os princípios da Política Nacional de Ciência Tecnologia e Inovação em Saúde (PNCTIS), orientandose pelo compromisso ético e social de contribuir para a melhoria das condições de saúde da população brasileira (Brasil, 2014). </p>
                <p  className="text-SaibaMais">Desde 2005, o setor saúde em todo o mundo vem sendo motivado a estabelecer e fortalecer mecanismos de tradução do conhecimento científico para apoiar o desenvolvimento da saúde pública, mediante políticas e sistemas de saúde guiados por evidências. Assim, neste mesmo ano, a Organização Mundial da Saúde (OMS) criou a <b>Evidence-Informed Policy Network (EVIPNet)</b> que é uma iniciativa global que abrange abordagens de ponta para a tradução do conhecimento para uma melhor formulação de políticas de saúde. </p>
                <p  className="text-SaibaMais">A <b>Rede de Políticas Informadas por Evidências do Brasil (Rede EVIPNet Brasil)</b> nasceu desse movimento e se consolidou no Brasil a partir de 2007, sendo institucionalizada pelo Ministério da Saúde, por meio da Portaria nº 2.636/GM/MS, de 7 de outubro de 2009, e atualizada pela Portaria de Consolidação nº 3 de 28 de setembro de 2017, em específico o Art. 5º Inciso XI que dispõe sobre as Políticas Informadas por Evidências (EVIDENCEINFORMED POLICY NETWORK – EVIPNET), na forma do Anexo XXV. A Rede EVIPNet Brasil é coordenada pelo Departamento de Ciência e Tecnologia da Secretaria de Ciência, Tecnologia, Inovação e Complexo da Saúde do Ministério da Saúde (DECIT/SECTICS/MS) e integrada por Núcleos de Evidências em Saúde (NEv), cujo objetivo é fortalecer políticas e sistemas de saúde pública mediante o uso sistemático de evidências nos processos de tomada de decisão. Os NEv’s, em operação no Brasil, colaboram com a melhoria da capacidade de tomada de decisões informadas com base na produção e uso sistemático de evidências.</p>
                <p  className="text-SaibaMais">O <b>NEv</b> pode ser compreendido como um <b>setor “intermediário de evidências”</b>, ou seja, um tipo de organização (representada por governos, universidades, terceiro setor ou setor privado) que têm por objetivo incentivar o uso das melhores evidências científicas, na elaboração, implantação e monitoramento de políticas nas diferentes instâncias do SUS, além de divulgar atividades de saúde baseada em evidências e disseminar conhecimento em saúde baseada em evidências para os demais profissionais, gestores e sociedade. Objetiva: a) Fortalecer políticas e sistemas de saúde pública; b) Colaborar com a melhoria da capacidade de tomada de decisões informadas; c) Favorecer o uso sistemático de evidências nos processos de tomada de decisão; d) Incentivar o uso das melhores evidências científicas na elaboração, implantação e monitoramento de políticas nas diferentes instâncias do SUS; 5) Contribuir com o trabalho da EVIPNet Brasil na difusão e capacitação para uso da metodologia Support para políticas informadas por evidências.</p>
            </div>
            <h2 className="title-descricao">QUEM SOMOS?</h2>
            <div className= "TextGrup">
                <p className="text-SaibaMais"><b>O Núcleo de Evidências em Saúde do Maranhão (NEv-MA)</b>, intitulado <b>Rede Aberta de Pesquisa do Núcleo de Evidências em Saúde do Maranhão (REPNEv-MA)</b>, é um núcleo de pesquisa em saúde que foi criado em janeiro de 2024, de caráter consultivo, de natureza técnico-científica sendo constituído por grupos de trabalhos com expertise na busca e avaliação de evidências científicas, produzidas pela pesquisa  em saúde, e por pesquisadores da graduação e pós-graduação da Universidade Federal do Maranhão (UFMA), além do setor em saúde a nível estadual e municipal do Maranhão e de outros estados. A REPNEv-MA está integrada ao Grupo de Pesquisa em Educação, Novas Tecnologias e Evidências (GEPETev), da UFMA. É institucionalizado no âmbito acadêmico da UFMA, e integra a <b>Rede para Políticas Informadas por Evidências (Rede EVIPNet Brasil)</b> vinculada à Coordenação-Geral de Evidências em Saúde, por meio do Departamento de Ciência e Tecnologia da Secretaria de Ciência, Tecnologia e Inovação e do Complexo Econômico-Industrial da Saúde (CGEVI/DECIT/SECTICS/MS). Rede EVIPNet Brasil tem como objetivo promover o uso sistemático e transparente de evidências no âmbito da saúde pública, mediante o intercâmbio entre gestores, pesquisadores e representantes da sociedade civil. Faz parte também da Coalizão Brasileira pelas Evidências e da Rede Nacional de Direitos Humanos (ReneDH).</p>
            </div>
            <div className="button-div">
                <button className="buttonSaibaMais" onClick={navigate('/')}><p>Quem somos ?</p></button>
            </div>
           
        </div>
    )
}
export default SaibaMais;